[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bcrypt==4.0.1",
    "fastapi>=0.136.1",
    "httpx>=0.28.1",
    "joblib>=1.5.3",
    "numpy>=2.4.6",
    "openai>=2.36.0",
    "passlib>=1.7.4",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings>=2.14.1",
    "pydantic[email]>=2.13.4",
    "python-dotenv>=1.2.2",
    "python-jose[cryptography]>=3.5.0",
    "python-levenshtein>=0.27.3",
    "python-multipart>=0.0.28",
    "python-whois>=0.9.6",
    "sqlalchemy>=2.0.49",
    "uvicorn[standard]>=0.46.0",
]
